name: golfanalysis_jpn
description: Flutter Machine Learning Project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.1.5
  flutter_camera: ^0.1.1
  video_player: ^2.4.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/home/
    - assets/guide/
    - assets/result/


